[nrf nout] Constant size for psa_core_key_attributes_t struct
nrfconnect/sdk-mbedtls pull request #12
Opened 2022-09-30 14:16 UTC by mswarowsky

Before the size would change depending on if MBEDTLS_PSA_CRYPTO_KEY_ID_ENCODES_OWNER is defined or not. This can cause problems when used in different domains. Example:
MBEDTLS_PSA_CRYPTO_KEY_ID_ENCODES_OWNER can not be enabled if PSA_CRYPTO is enabled. So if building an application as non-secure that uses PSA_CRYPTO MBEDTLS_PSA_CRYPTO_KEY_ID_ENCODES_OWNER will not be defined. causing id to just be psa_key_id_t(4 bytes), but TF-M running on the secure domain needs MBEDTLS_PSA_CRYPTO_KEY_ID_ENCODES_OWNER to be enabled, causing the id field to be a struct that is 8 byte when TF-M is built it is linked to the cc3xx runtime library that is built with MBEDTLS_PSA_CRYPTO_KEY_ID_ENCODES_OWNER not defined. As a result, psa_core_key_attributes_t is interpreted differently within the secure domain.

To just build the provided cc3xx library with MBEDTLS_PSA_CRYPTO_KEY_ID_ENCODES_OWNER enabled is not a real option as the library is meant to be also used for a secure domain-only application, that uses PSA_CRYPTO.

Signed-off-by: Markus Swarowsky <markus.swarowsky@nordicsemi.no>

## Status
**IN DEVELOPMENT**

2022-10-03 14:02 UTC, vili-nordic approved these changes

2022-10-10 06:32 UTC, frkv commented on include/psa/crypto_struct.h
> +/* This ensures that size of struct doesn't change size depending on the define
Can be simplified: "depending on setting MBEDTLS_PSA_CRYPTO_KEY_ID_ENCODES_OWNER "

2022-10-10 06:32 UTC, frkv commented on include/psa/crypto_struct.h
> + * This provides a compatablie version of initialisation.
Typo: Compatiblie => compatible

2022-10-10 06:33 UTC, frkv approved these changes
Approved, assuming minor NITS in comments is fixed, and the commit-message adds jira-number

2022-10-10 09:19 UTC, SebastianBoe requested changes
typo in sauce tag.

[nrf nout]

2022-10-10 11:25 UTC, SebastianBoe commented
noup's need a detailed rationale in the commit message for why a fromtree/fromlist has not been used.

2022-10-10 11:26 UTC, SebastianBoe requested changes
changes requested

2022-10-10 14:16 UTC, mswarowsky commented
> noup's need a detailed rationale in the commit message for why a fromtree/fromlist has not been used.

Ok if I understood this correct the Question is: Why this change is not going upstream?

2022-10-11 07:26 UTC, Vge0rge commented on include/psa/crypto_struct.h
> +/* This ensures that size of struct doesn't change size ddepending on setting
ddepending -> depending

2022-10-11 10:31 UTC, Vge0rge approved these changes

2022-10-11 10:42 UTC, mswarowsky commented
> noup's need a detailed rationale in the commit message for why a fromtree/fromlist has not been used.

I added an explanation to the commit msg, please recheck

2022-10-12 12:32 UTC, SebastianBoe commented on include/psa/crypto_struct.h
> +#define MBEDTLS_KEY_ATTRIBUTE_RESERVED_INIT (int32_t) 0
Should this be placed at line 353 to reduce it's scope?

(reduced scope gives more maintainable code)

2022-10-12 12:35 UTC, SebastianBoe requested changes
We should avoid noup if possible.

2022-10-13 11:20 UTC, mswarowsky commented
Will wait for upstream support of PSA_CRYPTO and ENCODES_OWNER added here: https://github.com/Mbed-TLS/mbedtls/pull/5380

2022-10-13 11:20 UTC, closed without merging