mbedtls: Constant size for psa core key attributes
nrfconnect/sdk-mbedtls pull request #13
Opened 2022-10-23 22:16 UTC by frkv

-Add support for constant size for psa_core_key_attributes_t with and without TF-M enabled
-Add better support for TLS/DTLS when using MBEDTLS_USE_PSA_CRYPTO

ref: NCSDK-17464

igned-off-by: Frank Audun Kvamtrø <frank.kvamtro@nordicsemi.no>

2022-10-24 07:27 UTC, mswarowsky approved these changes

2022-10-24 07:32 UTC, Vge0rge approved these changes
LGTM

2022-10-24 09:35 UTC, joerchan approved these changes

2022-10-26 13:20 UTC, SebastianBoe requested changes
noup commits must include the plan for how to get rid of the noup commit.

E.g.

noup commit can be removed when NCSDK-xxxx is solved.

2022-11-08 13:52 UTC, frkv commented
> noup commits must include the plan for how to get rid of the noup commit.
> 
> E.g.
> 
> noup commit can be removed when NCSDK-xxxx is solved.

The referenced Jira is the only information, available right now. We don't have actionable plan to solve this incompatibility

2022-11-10 12:52 UTC, SebastianBoe approved these changes
A plan for getting rid of the technical debt incurred by the noup has been devised.

2022-11-10 13:20 UTC, SebastianBoe requested changes
fromtree is used, but it is not clear why, as the noup commit alone solves NCSDK-17464.

It appears that it is not correct to reference 17464 from the fromtree commit?

fromtree's commits, even with a green CI, have a risk of introducing serious bugs and should only be used when necessary. Especially a fromtree commit of this nature, that modifies behaviour, not just adds functionality.

2022-11-10 13:40 UTC, SebastianBoe approved these changes

2022-11-14 10:16 UTC, merged