[nrf fromlist] ECP: Fix parameter A for random curves
nrfconnect/sdk-mbedtls pull request #14
Opened 2022-11-02 14:33 UTC by krish2718

As per [1] only Koblitz curves has a zero group curve parameter A, and random curves have non-zero parameter.

Fix parameter A for all random curves to align with [2].

[1] - https://www.secg.org/sec2-v2.pdf
[2] - https://datatracker.ietf.org/doc/rfc5114/

Signed-off-by: Krishna T <krishna.t@nordicsemi.no>
((cherry picked from PR 6528, without changes to tests)

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

## Status
**READY/IN DEVELOPMENT/HOLD**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

Yes | NO  
Which branch?

## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2022-11-09 08:04 UTC, SebastianBoe commented
https://github.com/Mbed-TLS/mbedtls/pull/6528

2022-11-14 07:20 UTC, sachinthegreen approved these changes

2022-11-15 12:15 UTC, SebastianBoe requested changes
An mbedtls developer believes this to be a spec./doc. bug, not an implementation bug.

Should we await merging this until it is clear whether this is a bug in the implementation or the spec. ?

2022-12-02 07:41 UTC, krish2718 commented
Closing this as per the upstream comment, it has been worked around in https://github.com/nrfconnect/sdk-hostap/pull/47

2022-12-02 07:41 UTC, closed without merging