[nrf noup] Add driver_wrapper call for derivation
nrfconnect/sdk-mbedtls pull request #2
Opened 2022-01-30 13:09 UTC by Vge0rge

-This adds a psa_driver_wrapper call for the PSA
 psa_key_derivation_key_agreement API.

Ref: NCSDK-13564

Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>

2022-02-02 08:41 UTC, tejlmand requested changes
The PR description and / or commit message should be much clearer as to why exactly do we need to patch mbedTLS, and why can't this be done in nrfxlib repo.

We usually can pick exactly the source files we need in the CMakeLists.txt files in sdk-nrfxlib repo.

2022-02-03 16:19 UTC, Vge0rge commented
> The PR description and / or commit message should be much clearer as to why exactly do we need to patch mbedTLS, and why can't this be done in nrfxlib repo.
> 
> We usually can pick exactly the source files we need in the CMakeLists.txt files in sdk-nrfxlib repo.

Please check the new description and accept if possible :)

2022-02-03 20:18 UTC, tejlmand approved these changes

2022-02-04 07:56 UTC, joerchan approved these changes

2022-02-04 09:00 UTC, SebastianBoe approved these changes

2022-02-04 19:05 UTC, merged