[nrf noup] Fix merge error
nrfconnect/sdk-mbedtls pull request #7
Opened 2022-06-29 23:17 UTC by plskeggs

MBEDTLS_SSL_DTLS_CONNECTION_ID fails to build now because ad_len_field
is defined twice.  Remove the extra one.

Signed-off-by: Pete Skeggs <peter.skeggs@nordicsemi.no>

2022-06-30 12:53 UTC, joerchan commented
@plskeggs Can you please clarify the commit message. It does not appear to be a problem related to the merge itself.

Can you update the commit message to:
```
[nrf noup] Fix duplicate declaration of ad_len_field

MBEDTLS_SSL_DTLS_CONNECTION_ID fails to build now because ad_len_field
is defined twice. Remove the extra one.

Regression from: cf39070d6e3e36e1ed65f970545bf6bcc1b1fc8a
Should be squashed with that commit in next upmerge or rebase.

Signed-off-by: Pete Skeggs [peter.skeggs@nordicsemi.no](mailto:peter.skeggs@nordicsemi.no)
```

2022-06-30 19:22 UTC, Vge0rge commented
> @plskeggs Can you please clarify the commit message. It does not appear to be a problem related to the merge itself.
> 
> Can you update the commit message to:
> 
> ```
> [nrf noup] Fix duplicate declaration of ad_len_field
> 
> MBEDTLS_SSL_DTLS_CONNECTION_ID fails to build now because ad_len_field
> is defined twice. Remove the extra one.
> 
> Regression from: cf39070d6e3e36e1ed65f970545bf6bcc1b1fc8a
> Should be squashed with that commit in next upmerge or rebase.
> 
> Signed-off-by: Pete Skeggs [peter.skeggs@nordicsemi.no](mailto:peter.skeggs@nordicsemi.no)
> ```

I agree with this, please update the commit message.

2022-07-05 22:06 UTC, plskeggs commented
> > @plskeggs Can you please clarify the commit message. It does not appear to be a problem related to the merge itself.
> > Can you update the commit message to:
> > ```
> > [nrf noup] Fix duplicate declaration of ad_len_field
> > 
> > MBEDTLS_SSL_DTLS_CONNECTION_ID fails to build now because ad_len_field
> > is defined twice. Remove the extra one.
> > 
> > Regression from: cf39070d6e3e36e1ed65f970545bf6bcc1b1fc8a
> > Should be squashed with that commit in next upmerge or rebase.
> > 
> > Signed-off-by: Pete Skeggs [peter.skeggs@nordicsemi.no](mailto:peter.skeggs@nordicsemi.no)
> > ```
> 
> I agree with this, please update the commit message.

Done, @joerchan and @Vge0rge.

2022-07-06 08:20 UTC, Vge0rge approved these changes
LGTM

2022-07-06 13:10 UTC, sigvartmh approved these changes

2022-07-12 08:44 UTC, Vge0rge commented
@plskeggs  I just opened an sdk-nrf PR based on your mbedtls PR here:
https://github.com/nrfconnect/sdk-nrf/pull/8162

We need to have a green CI in order to ask to merge this (FYI I don't have merge rights for the repo).

2022-07-12 08:53 UTC, frkv commented
This also needs to go through full CI as it reaches into all projects. We need to wait for the ongoing upmerge to finalize before taking this in. We're starting CI tests now and will rebase it later

2022-07-21 08:28 UTC, joerchan approved these changes
@Vge0rge Could you rebase the manifest PR now that the upmerge is finished?

2022-07-21 08:50 UTC, Vge0rge commented
> @Vge0rge Could you rebase the manifest PR now that the upmerge is finished?

Just rebased and force pushed. Lets see the CI and merge if it is ok

2022-07-29 00:34 UTC, plskeggs commented
Can this get merged now?

2022-08-01 09:03 UTC, carlescufi requested changes
Why is this `[noup]` ?

2022-08-01 09:39 UTC, joerchan commented
> Why is this `[noup]` ?

Because it fixes a mistake in backporting a commit from upstream, so it is a downstream only problem.
There is a note in the commit message to squash this commit in the next upmerge / rebase.

2022-08-02 12:34 UTC, carlescufi commented
> > Why is this `[noup]` ?
> 
> Because it fixes a mistake in backporting a commit from upstream, so it is a downstream only problem. There is a note in the commit message to squash this commit in the next upmerge / rebase.

Then please use the format here:
https://github.com/nrfconnect/sdk-zephyr/pull/567/commits/907f297f9b48f4bbdf8046b4e86111e67574be6d

2022-08-02 12:41 UTC, carlescufi approved these changes

2022-08-02 12:41 UTC, merged